name: shelf_dart
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
